sudo: false
language: node_js
node_js:
- iojs
- '0.12'
- '0.10'
before_install:
- openssl aes-256-cbc -K $encrypted_0777195b3608_key -iv $encrypted_0777195b3608_iv
  -in credentials.json.enc -out credentials.json -d
